### ISSUE TITLE
its rokebn

### ISSUE THREAD

**Issue by barrack-obama** [RealistikDash/GDPyS-v4#1]
its broken please fix

- [x] fix problem

**Comment by xSkyyy** [comment]
i fix problem pay me 20 quid

**Comment by RealistikDash** [comment]
Problem fixed. For free.

**Comment by xSkyyy** [comment]
i have been exposed as a scammer 😔

**Comment by barrack-obama** [comment]
> i have been exposed as a scammer 😔 

Don't care + ratio

**Comment by xSkyyy** [comment]
crying rn
